# Generated by Django 6.0.3 on 2026-03-21 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_status', models.CharField(choices=[('YTS', 'Yet To Start'), ('WIP', 'Work In Progress'), ('HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='YTS', max_length=20)),
                ('task_start_date', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.CharField(max_length=100, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('ABD', 'ABD'), ('DSA', 'DSA'), ('FDS', 'FDS')], max_length=10)),
                ('cab_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
